#!/bin/bash

FILE="__pycache__/upload*.pyc"

if [ $FILE -ot "upload.py" ]; then

    if [ -d "__pychache__" ]; then
        rm __pycache__/upload*.pyc
    fi
    python3 -m compileall "upload.py"
fi

python3 $FILE
